title: Abeaufays
description: My personal blog.

theme: minima

github_username: abeaufays
linkedin_username: alexandrebeaufays
mastodon:
  - username: abeaufays
    instance: mastodon.social

minima:
  skin: auto

